CREATE TABLE users (
  id BIGINT NOT NULL,
  name VARCHAR(255) DEFAULT NULL,
  email VARCHAR(255) DEFAULT NULL,
  password VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE addresses (
  id BIGINT NOT NULL,
  street VARCHAR(255) DEFAULT NULL,
  city VARCHAR(255) DEFAULT NULL,
  zip VARCHAR(20) DEFAULT NULL,
  user_id BIGINT DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT address_fk FOREIGN KEY (user_id) REFERENCES users (id)
);
